version: '3.1'
services:
  web: 
    environment:
      - FLASK_APP=main.py
      - FLASK_DEBUG=1
    command: flask run --host=0.0.0.0
    env_file: ./app/.env
    ports: 
      - 8080:80  
    build: ./ 
    volumes:
      - ~/.aws/:/root/.aws
    depends_on:
      - redis
    command:
      bash -c "sh /start.sh &  rq worker -u redis://redis:6379"
  redis:
    image: "redis:alpine" 