# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
# circle 빌드테스트 구성해야함
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.7-stretch-browsers
        environment:
          FLASK_CONFIG: testing
          TEST_DATABASE_URL: $SQLALCHEMY_DATABASE_URI
      - image: circleci/mysql:5.7
        environment:
          MYSQL_USER: root
          MYSQL_DATABASE: test-db 
    working_directory: ~/repo 
    steps:
      - checkout 
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      # run tests!
      - run:
          name: run tests
          command: | 
            python app/main.py db init
            python app/main.py db migrate
            python app/main.py db upgrade
            python initdb.py
            nose2

      - store_artifacts:
          path: test-reports
          destination: test-reports
