"""empty message

Revision ID: df5510089a22
Revises: 
Create Date: 2021-03-21 05:47:14.520003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df5510089a22'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('balance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'credit', 'users', ['user_id'], ['id'])
    op.add_column('invoice', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'invoice', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'keypair', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'subnets', 'user_vpc', ['vpc_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subnets', type_='foreignkey')
    op.drop_constraint(None, 'keypair', type_='foreignkey')
    op.drop_constraint(None, 'invoice', type_='foreignkey')
    op.drop_column('invoice', 'user_id')
    op.drop_constraint(None, 'credit', type_='foreignkey')
    op.drop_table('balance')
    # ### end Alembic commands ###
